import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  container: {
    direction: 'rtl',
    padding: `${theme.spacing(3)} 0 !important`,
  },
  card: {
    padding: theme.spacing(2),
    borderRadius: '12px !important',
    boxShadow: '0 18px 45px rgba(38, 0, 92, 0.12) !important',
    border: '1px solid rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(2),
    [theme.breakpoints.up('md')]: {
      flexDirection: 'row',
    },
    marginTop: theme.spacing(1.5),
  },
  mapColumn: {
    flex: '0 0 230px',
    display: 'flex',
    flexDirection: 'column',
  },
  mapIframe: {
    border: 0,
    borderRadius: 8,
    width: '100%',
    height: '100%',
  },
  infoColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
  },
  hospitalInfoRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing(1.25),
  },
  hospitalImage: {
    width: 60,
    height: 60,
    objectFit: 'cover',
    borderRadius: theme.shape?.borderRadius ?? 8,
    flexShrink: 0,
  },
  hospitalTextInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.5),
    flex: 1,
  },
  hospitalTitle: {
    fontWeight: 'bold !important',
    fontSize: '1.1rem !important',
    color: '#717171 !important',
  },
  hospitalLocation: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing(0.5),
  },
  locationIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
  },
  hospitalAddress: {
    color: '#717171 !important',
    fontSize: '0.75rem !important',
  },
  divider: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: '#E0E0E0',
    height: '2px',
  },
  appointmentInfoRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
  },
  infoItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  infoIcon: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
  },
  infoText: {
    fontSize: '12px !important',
    color: '#292D32 !important',
  },
  buttonContainer: {
    marginTop: theme.spacing(3),
  },
  sectionTitle: {
    fontSize: '0.75rem !important',
    color: '#717171 !important',
    fontWeight: 'bold !important',
    marginBottom: theme.spacing(1.5),
  },
  formCard: {
    padding: theme.spacing(2),
    borderRadius: '12px !important',
    boxShadow: '0 18px 45px rgba(38, 0, 92, 0.12) !important',
    border: '1px solid rgba(0, 0, 0, 0.12)',
    marginTop: theme.spacing(1.5),
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  paymentOptions: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1),
    marginTop: theme.spacing(1.5),
  },
  paymentBox: {
    borderRadius: '12px',
    border: '1px solid #EDEDED',
    padding: theme.spacing(2),
    position: 'relative',
    overflow: 'hidden',
  },
  paymentBoxInner: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    position: 'relative',
    zIndex: 1,
  },
  paymentBoxContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    flex: 1,
    marginRight: '16px',
  },
  paymentImage: {
    height: '40px',
    width: 'auto',
    objectFit: 'contain',
    flexShrink: 0,
  },
  paymentBadge: {
    background: '#FFD3D3',
    border: '1px solid #EE9898',
    borderRadius: '10px',
    padding: '4px 8px',
    fontSize: '10px !important',
    color: '#3C3A3A !important',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  paymentBoxTitle: {
    fontSize: '0.75rem !important',
    color: '#3b3b3b !important',
    fontWeight: 'bold !important',
  },
  paymentBoxDetails: {
    fontSize: '0.75rem !important',
    color: '#7b7b7b !important',
  },
  paymentCheckIcon: {
    width: '28px',
    height: '28px',
    flexShrink: 0,
    position: 'relative',
    zIndex: 2,
  },
  paymentEmptyCircle: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    border: '2px solid #EDEDED',
    flexShrink: 0,
    position: 'relative',
    zIndex: 2,
  },
  submitButton: {
    paddingTop: '16px !important',
    paddingBottom: '16px !important',
  },
  submitButtonContainer: {
    marginTop: '16px !important',
    width: '100%',
  },
  submitButtonFixed: {
    display: 'none',
    [theme.breakpoints.down('sm')]: {
      display: 'block',
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      padding: theme.spacing(2),
      backgroundColor: '#fff',
      boxShadow: '0 -4px 16px rgba(0, 0, 0, 0.1)',
      zIndex: 1000,
      direction: 'rtl',
      maxWidth: '100vw',
      boxSizing: 'border-box',
      animation: '$slideUp 0.3s ease-out',
    },
  },
  '@keyframes slideUp': {
    from: {
      transform: 'translateY(100%)',
    },
    to: {
      transform: 'translateY(0)',
    },
  },
}));
