import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles((theme) => ({
  root: {
    width: '100%',
    display: 'flex',
    alignItems: 'stretch',
    marginBottom: theme.spacing(2),
    position: 'relative',
    zIndex: 1,
  },
  layout: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
    [theme.breakpoints.up('lg')]: {
      flexDirection: 'row',
    },
  },
  leftColumn: {
    flex: '0 1 460px',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(2),
    [theme.breakpoints.down('sm')]: {
      gap: theme.spacing(1),
    },
  },
  filterRow: {
    display: 'flex',
    gap: theme.spacing(2),
    flexDirection: 'row',
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column-reverse',
      gap: theme.spacing(1),
    },
  },
  selectControl: {
    backgroundColor: theme.palette.background.paper,
    borderRadius: theme.shape?.borderRadius ?? 12,
    boxShadow: '0 4px 16px rgba(18, 3, 50, 0.08)',
    paddingInline: theme.spacing(2),
    paddingBlock: theme.spacing(1),
    '& .MuiInputBase-root': {
      borderRadius: theme.shape?.borderRadius ?? 12,
    },
  },
  specialitySelectWrapper: {
    flex: '1.5 1 0',
  },
  citySelectWrapper: {
    flex: '1 1 0',
  },
  card: {
    padding: theme.spacing(3),
    borderRadius: '10px !important',
    border: '1px solid #EDEDED',
    boxShadow: '0 18px 45px rgba(38, 0, 92, 0.12) !important',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
  },
  cardFirstRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing(2),
    direction: 'rtl',
  },
  hospitalInfoColumn: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing(1.25),
    flex: 1,
  },
  hospitalImage: {
    width: 60,
    height: 60,
    objectFit: 'cover',
    borderRadius: theme.shape?.borderRadius ?? 8,
    flexShrink: 0,
  },
  hospitalTextInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(0.5),
    flex: 1,
  },
  hospitalTitleRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    width: '100%',
  },
  hospitalTitle: {
    fontWeight: 'bold !important',
    fontSize: '1.1rem !important',
    color: '#717171 !important',
  },
  hospitalLocation: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing(0.5),
  },
  locationIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
  },
  hospitalAddress: {
    color: '#717171 !important',
    fontSize: '0.75rem !important',
  },
  ratingBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(0.5),
  },
  starIcon: {
    color: '#FFB800',
    fontSize: '1.25rem !important',
  },
  ratingText: {
    fontSize: '.75rem !important',
    color: '#717171 !important',
  },
  cardDivider: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: '#E0E0E0',
    height: '2px',
    margin: 0,
  },
  cardSecondRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
    direction: 'rtl',
  },
  infoRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  infoRowIcon: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
  },
  infoTextWithTick: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(0.5),
    flex: 1,
  },
  infoRowText: {
    fontSize: '12px !important',
    color: '#292D32 !important',
  },
  tickIcon: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
  },
  whatsappBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(0.75),
    backgroundColor: '#F8E9FB',
    padding: `${theme.spacing(0.5)} ${theme.spacing(1)}`,
    borderRadius: theme.shape?.borderRadius ?? 6,
    textDecoration: 'none',
    '&:hover': {
      opacity: 0.9,
    },
  },
  whatsappIcon: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
  },
  whatsappNumber: {
    fontSize: '12px !important',
    color: '#292D32 !important',
    direction: 'ltr !important',
    whiteSpace: 'nowrap',
  },
  whatsappAvatar: {
    backgroundColor: '#ECF8F1',
    width: 36,
    height: 36,
    padding: 6,
    img: {
      width: '100%',
      height: '100%',
      objectFit: 'contain',
    },
  },
  paymentSection: {
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(1),
    marginLeft: `calc(-1 * ${theme.spacing(2)})`,
    marginRight: `calc(-1 * ${theme.spacing(2)})`,
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    overflow: 'hidden',
    [theme.breakpoints.up('sm')]: {
      marginLeft: `calc(-1 * ${theme.spacing(3)})`,
      marginRight: `calc(-1 * ${theme.spacing(3)})`,
      paddingLeft: theme.spacing(3),
      paddingRight: theme.spacing(3),
    },
  },
  paymentContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    width: 'fit-content',
    [theme.breakpoints.down('md')]: {
      animation: '$paymentMarquee 80s linear infinite',
      willChange: 'transform',
    },
    [theme.breakpoints.down('sm')]: {
      animation: '$paymentMarquee 50s linear infinite',
      willChange: 'transform',
    },
    [theme.breakpoints.up('md')]: {
      justifyContent: 'center',
      width: '100%',
    },
  },
  paymentImage: {
    height: 60,
    width: 'auto',
    objectFit: 'contain',
    flexShrink: 0,
  },
  '@keyframes paymentMarquee': {
    '0%': {
      transform: 'translateX(0)',
    },
    '100%': {
      transform: 'translateX(-50%)',
    },
  },
  appointmentSkeleton: {
    padding: theme.spacing(3),
    borderRadius: '10px !important',
    border: '1px solid #EDEDED',
    boxShadow: '0 18px 45px rgba(38, 0, 92, 0.12) !important',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
    direction: 'rtl',
  },
}));
